name: pysfg
channels:
  - javascript
  - conda-forge
  - defaults
dependencies:
- python=3.8
- pip=20.1.1
- numpy=1.18.5
- pandas=1.0.5
- matplotlib=3.3.1
- pyqt=5.9.2
- jupyterlab=2.1.5
- widgetsnbextension=3.5.1
- ipywidgets=7.5.1
- ipykernel=5.3.2
- iminuit=1.4.5
- altair=4.1.0
- nodejs=10.13.0
- scipy=1.5.0
- pyaml=19.4.1
- xmltodict=0.12.0
- pip:
    - --editable .
